spring:
  application:
    name: result-service

datasource:
    url: jdbc:postgresql://localhost:5433/labcloud_result
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

security:
  jwt:
    secret: chave-secreta-jwt-compartilhada-entre-todos-os-servicos-labcloud-2026-esta-e-a-chave
    expiration: 86400000

server:
  port: 8083

auth:
  service:
    url: http://localhost:8081

sample:
  service:
    url: http://localhost:8082

logging:
  level:
    com.labcloud: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG